name: moveapps-python-sdk
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - geopandas
  - movingpandas
  - pluggy
  - python-dotenv
  - matplotlib
  - shapely
  - networkx
  - osmnx
  - cython
  - geoviews-core
